#!/bin/bash

# Import golangrc
source ~/.golangrc

# This is for the tmux powerline
PS1="$PS1"'$([ -n "$TMUX" ] && tmux setenv TMUXPWD_$(tmux display -p "#D" | tr -d %) "$PWD")'

# Setup oh-my-zsh and theme
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="ys"
COMPLETION_WAITING_DOTS="true"
plugins=(git osx)
source $ZSH/oh-my-zsh.sh

# Set editor
if [ -f /usr/local/bin/vim ]; then
    export EDITOR=/usr/local/bin/vim
fi
