#!/bin/bash

# Setup oh-my-zsh and theme
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="xiong-chiamiov-plus"
COMPLETION_WAITING_DOTS="true"
plugins=(git osx)
source $ZSH/oh-my-zsh.sh

# Set editor
if [ -f /usr/bin/vim ]; then
    export EDITOR=/usr/bin/vim
fi
